# This file stores configurations for your Shopify app.

scopes = "read_script_tags,write_script_tags,read_products,write_products,write_themes,read_themes,read_draft_orders,write_draft_orders,read_markets,write_markets"
